# Site settings
title: ARTISAN CODE
email: tom@artisancode.co.uk
description: Software craftsmanship by design
url: "https://www.artisancode.co.uk"
twitter_username: Tom_Kuhn
github_username:  Tom-Kuhn
linkedin_url: https://www.linkedin.com/profile/view?id=82578011
stackoverflow_url: http://stackoverflow.com/users/1816/tk

# Build settings
# permalink: pretty
permalink: /:year/:month/:slug
paginate: 5
exclude: ["node_modules"]

excerpt_separator: \n\n

#gem settings
highlighter: rouge

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    css_class: 'highlight'
